spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/gdpr
    username: george
    password: 4434
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false
  ssl:
    key-store: classpath:KeyStore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: mydomain
    key-password: password
    enabled: true
  port: 8443
security:
  require-ssl: true